#!/usr/bin/ruby

require 'fileutils'

EOL = "\n"

dirs = Dir["*"].select { |f| File.directory?(f) }

if dirs.empty?
  puts "No data directories found. Run `../in2csv.rb` first."
  Process.exit
end

File.open("analyses.R", "w") { |f|
  f.write("# Generated by generateR.rb" + EOL*2)
  
  dirs.each { |dir|
    f.write(EOL + "# #{dir}" + EOL*2)
    
    # Load plain data
    f.write("#{dir}_products <- read.csv(\"#{dir}/products.csv\")" + EOL)
    f.write("#{dir}_ordersXprod <- as.matrix(read.table(\"#{dir}/orderXprod.csv\", colClasses=\"integer\"))" + EOL)
        
    # Histogram of product weights
    f.write("hist(#{dir}_products$weight, xlab=\"weight\", ylab=\"nr of products\", main=\"#{dir}\")" + EOL)
    # Histogram of order weights
    f.write("hist(#{dir}_ordersXprod %*% #{dir}_products$weight, xlab=\"weight\", ylab=\"nr of orders\", main=\"#{dir}\")" + EOL)
  }
  
  puts "Analysis script written. Run `R -f analyses.R` to process."
}
